name: viper
channels:
- bioconda
- hcc
- r
- quasiben
dependencies:
- bedtools=2.25.0=1
- bioconductor-annotate=1.48.0=1
- bioconductor-annotationdbi=1.32.2=0
- bioconductor-annotationforge=1.12.2=0
- bioconductor-biobase=2.30.0=0
- bioconductor-biocgenerics=0.16.1=r3.2.2_0
- bioconductor-biocparallel=1.4.3=r3.2.2_0
- bioconductor-biomart=2.26.1=r3.2.2_0
- bioconductor-biostrings=2.38.2=0
- bioconductor-category=2.36.0=r3.2.2_0
- bioconductor-clusterprofiler=2.4.3=0
- bioconductor-complexheatmap=1.6.0=1
- bioconductor-deseq2=1.10.0=r3.2.2_1
- bioconductor-do.db=2.9=0
- bioconductor-dose=2.8.2=0
- bioconductor-edger=3.12.0=0
- bioconductor-gage=2.21.1=0
- bioconductor-gagedata=2.8.0=0
- bioconductor-genefilter=1.52.0=r3.2.2_0
- bioconductor-geneplotter=1.48.0=0
- bioconductor-genomeinfodb=1.6.1=0
- bioconductor-genomicranges=1.22.3=0
- bioconductor-go.db=3.2.2=0
- bioconductor-gosemsim=1.28.2=0
- bioconductor-gostats=2.36.0=0
- bioconductor-graph=1.48.0=0
- bioconductor-gseabase=1.32.0=0
- bioconductor-iranges=2.4.6=0
- bioconductor-kegggraph=1.28.0=r3.2.2_0
- bioconductor-keggrest=1.10.1=r3.2.2_0
- bioconductor-limma=3.26.7=1
- bioconductor-multtest=2.26.0=0
- bioconductor-org.hs.eg.db=3.2.3=0
- bioconductor-pathview=1.9.0=0
- bioconductor-qvalue=2.2.2=0
- bioconductor-rbgl=1.46.0=r3.2.2_0
- bioconductor-rgraphviz=2.14.0=0
- bioconductor-s4vectors=0.8.7=0
- bioconductor-summarizedexperiment=1.0.2=0
- bioconductor-sva=3.18.0=0
- bioconductor-topgo=2.22.0=0
- bioconductor-xvector=0.10.0=1
- bioconductor-zlibbioc=1.16.0=r3.2.2_1
- blast=2.2.31=1
- boost=1.60.0=py35_0
- cairo=1.12.18=6
- cufflinks=2.2.1=py35_1
- curl=7.45.0=1
- docutils=0.12=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- glib=2.43.0=2
- gmap=2015.09.10=0
- gmp=5.1.2=2
- gsl=1.16=1
- harfbuzz=0.9.39=0
- icu=54.1=0
- java-jdk=8.0.45=0
- jbig=2.1=0
- jpeg=8d=0
- libdb=6.1.26=0
- libffi=3.0.13=0
- libgcc=4.8.5=1
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.3=0
- mkl=11.3.1=0
- mysql=5.5.24=0
- ncurses=5.9=4
- numpy=1.10.4=py35_1
- openssl=1.0.2g=0
- pandas=0.17.1=np110py35_0
- pango=1.39.0=0
- pcre=8.31=0
- perl-db-file=1.835=5
- perl-scalar-list-utils=1.42=2
- perl-set-intervaltree=0.10=3
- perl-threaded=5.22.0=9
- perl-uri=1.69=2
- picard=1.141=1
- pip=8.1.1=py35_1
- pixman=0.32.6=0
- proj4=4.9.1=0
- python=3.5.1=0
- python-dateutil=2.5.1=py35_0
- pytz=2016.2=py35_0
- pyyaml=3.11=py35_1
- r=3.2.2=0
- r-acepack=1.3_3.3=r3.2.2_1a
- r-ash=1.0_15=r3.2.2_0
- r-assertthat=0.1=r3.2.2_1a
- r-base=3.2.2=0
- r-bh=1.58.0_1=r3.2.2_0a
- r-bitops=1.0_6=r3.2.2_1a
- r-boot=1.3_17=r3.2.2_0a
- r-brew=1.0_6=r3.2.2_1a
- r-calibrate=1.7.2=r3.2.2_0
- r-catools=1.17.1=r3.2.2_2a
- r-circlize=0.3.3=r3.2.2_0
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-colorspace=1.2_6=r3.2.2_0a
- r-curl=0.9.4=r3.2.2_0a
- r-dbi=0.3.1=r3.2.2_2a
- r-dendextend=1.1.2=r3.2.2_0
- r-devtools=1.9.1=r3.2.2_0a
- r-dichromat=2.0_0=r3.2.2_2a
- r-digest=0.6.9=r3.2.2_0
- r-doparallel=1.0.10=r3.2.2_0a
- r-dplyr=0.4.3=r3.2.2_0a
- r-evaluate=0.8=r3.2.2_0a
- r-foreach=1.4.3=r3.2.2_0a
- r-foreign=0.8_66=r3.2.2_0a
- r-formula=1.2_1=r3.2.2_0a
- r-futile.logger=1.4.1=r3.2.2_0
- r-futile.options=1.0.0=r3.2.2_0
- r-gdata=2.17.0=r3.2.2_0a
- r-getoptlong=0.1.0=r3.2.2_0
- r-ggalt=0.1.1=r3.2.2_0
- r-ggplot2=2.1.0=r3.2.2_0
- r-git2r=0.11.0=r3.2.2_0a
- r-globaloptions=0.0.8=r3.2.2_0
- r-gplots=2.17.0=r3.2.2_0a
- r-gridbase=0.4_7=r3.2.2_0a
- r-gridextra=2.0.0=r3.2.2_0a
- r-gtable=0.1.2=r3.2.2_2a
- r-gtools=3.5.0=r3.2.2_0a
- r-hmisc=3.17_0=r3.2.2_0a
- r-httr=1.0.0=r3.2.2_0a
- r-igraph=1.0.1=r3.2.2_0a
- r-irlba=2.0.0=r3.2.2_0a
- r-iterators=1.0.8=r3.2.2_0a
- r-jsonlite=0.9.19=r3.2.2_0
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-labeling=0.3=r3.2.2_1a
- r-lambda.r=1.1.7=r3.2.2_0
- r-lattice=0.20_33=r3.2.2_0a
- r-latticeextra=0.6_26=r3.2.2_2a
- r-lazyeval=0.1.10=r3.2.2_2a
- r-locfit=1.5_9.1=r3.2.2_0
- r-magrittr=1.5=r3.2.2_1a
- r-maps=3.0.0_2=r3.2.2_0
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-memoise=0.2.1=r3.2.2_1a
- r-mgcv=1.8_9=r3.2.2_0a
- r-mime=0.4=r3.2.2_0a
- r-multcomp=1.4_1=r3.2.2_0a
- r-munsell=0.4.2=r3.2.2_1a
- r-mutoss=0.1_10=r3.2.2_0
- r-mvtnorm=1.0_3=r3.2.2_0a
- r-nlme=3.1_122=r3.2.2_0a
- r-nmf=0.20.6=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-pkgmaker=0.22=r3.2.2_0a
- r-plotrix=3.6_1=r3.2.2_0
- r-plyr=1.8.3=r3.2.2_0a
- r-png=0.1_7=r3.2.2_2a
- r-proj4=1.0_8=r3.2.2_0
- r-proto=0.3_10=r3.2.2_1a
- r-r6=2.1.1=r3.2.2_0a
- r-rcolorbrewer=1.1_2=r3.2.2_2a
- r-rcpp=0.12.2=r3.2.2_0a
- r-rcpparmadillo=0.6.200.2.0=r3.2.2_0a
- r-rcurl=1.95_4.7=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-registry=0.3=r3.2.2_0a
- r-reshape2=1.4.1=r3.2.2_1a
- r-rjson=0.2.15=r3.2.2_0a
- r-rngtools=1.2.4=r3.2.2_0a
- r-roxygen2=5.0.1=r3.2.2_0a
- r-rpart=4.1_10=r3.2.2_0a
- r-rsqlite=1.0.0=r3.2.2_1a
- r-rstudioapi=0.3.1=r3.2.2_0a
- r-rversions=1.0.2=r3.2.2_0a
- r-sandwich=2.3_4=r3.2.2_0a
- r-scales=0.3.0=r3.2.2_0a
- r-shape=1.4.2=r3.2.2_0
- r-snow=0.4_1=r3.2.2_0
- r-sparsem=1.7=r3.2.2_0
- r-spatial=7.3_11=r3.2.2_0a
- r-stringi=1.0_1=r3.2.2_0a
- r-stringr=1.0.0=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-th.data=1.0_6=r3.2.2_1a
- r-viridis=0.3.1=r3.2.2_0
- r-whisker=0.3_2=r3.2.2_1a
- r-xml=3.98_1.3=r3.2.2_0a
- r-xml2=0.1.2=r3.2.2_0a
- r-xtable=1.8_0=r3.2.2_0a
- r-zoo=1.7_12=r3.2.2_1a
- readline=6.2=2
- samtools=1.2=2
- setuptools=20.3=py35_0
- six=1.10.0=py35_0
- snakemake=3.6.1=py35_0
- sqlite=3.9.2=0
- star=2.5.1b=0
- star-fusion=0.5.4=1
- tk=8.5.18=0
- ucsc-bedgraphtobigwig=324=0
- ucsc-bedsort=324=0
- ucsc-fetchchromsizes=324=0
- varscan=2.4.1=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0

