name: viper
channels: !!python/tuple
- bioconda
- conda-forge
- defaults
dependencies:
#GENERAL
- snakemake
- samtools
- python=3.5.2
- r=3.3.2

#align.snakefile
- star>=2.5.3a
- star-fusion
- bioconductor-sva

#cdr3.snakefile-
- pysam
- biopython
- r-venndiagram
- r-corrplot

#cluster.snakefile-
- r-ggrepel
- bioconductor-complexheatmap 
- r-circlize
- r-dplyr

#DE.snakefile
- bioconductor-deseq2>=1.12.1
- bioconductor-limma
- bioconductor-edger
- bioconductor-tximport
- r-readr
- r-calibrate

#gsea.snakefile
- bioconductor-clusterprofiler

#file_format.snakefile
- bedtools
- ucsc-bedsort
- ucsc-bedgraphtobigwig
- ucsc-fetchchromsizes

#immunology.snakefile
- r-crayon
- r-sqldf

#pathway.snakefile
- bioconductor-org.hs.eg.db
- bioconductor-org.mm.eg.db
- bioconductor-gostats
- r-ggalt
- r-mutoss
- bioconductor-gage
- bioconductor-gagedata
- bioconductor-pathview
- bioconductor-clusterprofiler

#readQC.snakefile
- picard

#rsem.snakefile
- rsem
- r-argparse

#snp.snakefile
- varscan
- snpeff

#virusseq.snakefile
- cufflinks

#tools
- bioconductor-biomart

#misc.
#BUG: missing libSM.so.6
- xorg-libsm