# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

#Metasheet with left or single mate, sample_name, condition1, condition2, ..., conditionN
#Right mate has to follow the same name convention as that of it's left mate, except for _R2_ . This will be _R1_ in left mate file name.
#Refer to https://github.com/vangalamaheshh/ROOT/blob/master/bioifx/pipelines/snakemake/metasheet.sample.csv
metasheet: metasheet.csv

#possible values are, True and False
stranded: True
# if stranded True, library_type is a required argument
# Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: fr-firststrand

# Tosh R code requires these params
#################
######PARAMS
##################
# Sample-Sample Heatmap params
RPKM_threshold: 2.0
min_num_samples_expressing_at_threshold: 4

# Number of genes to be represented in the Sample-Sample, Sample-Feature, and PCA plots
numgenes_plots: 1000

num_kmeans_clust: '0,4'

filter_mirna: True

# Varscan - default turned off 
snp_scan_genome: False

# VirusSeq module - possible values [True,False]
virus_dna_scan: False

# to perform a TRUST (cdr3) analysis.  refer to README.md
cdr3_analysis: False

# Pathway params
numgoterms: 10
goterm_adjpval_cutoff: 0.05
numkeggpathways: 5

#Uncomment the following line to perform TIMER (immunology) analysis. refer to README.md
#cancer_type: 'sarc'

# Batch params
batch_effect_removal: False

# sub-analyses
analysis_token: 
